### ISSUE TITLE
Examples in documentation are wrong. data-src instead of data-original

### ISSUE THREAD

**Issue by jackblackCH** [verlok/lazyload#138]

**Comment by verlok** [comment]
Right, the doc describes version 10, but if you use version 8 the default value is different. I will update it. Thanks

**Comment by verlok** [comment]
Fixed that - added an IMPORTANT section at the beginning of the doc with the link to the older documentation which is now in a separate file.

**Comment by tom10271** [comment]
I am not sure whether the important section is obvious enough or not as I realize what is going on until I read the source code

**Comment by verlok** [comment]
Hi @tom10271,
could you tell me what is it that you didn’t find easy to understand?

**Comment by tom10271** [comment]
The problem is I actually still unable to find the important notes. I think most people will only read the README.md in https://github.com/verlok/lazyload. It hints me to install v8, I do so and follow whatever in README.md and it is not working.
